// <auto-generated />
using System;
using EventSourcing_Pagamento.Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventSourcing_Pagamento.Infra.Migrations
{
    [DbContext(typeof(PagamentoContext))]
    [Migration("20200929223416_Migration_Initial")]
    partial class Migration_Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EventSourcing_Pagamento.Dominio.Pagamentos.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Aprovado")
                        .HasColumnType("bit");

                    b.Property<string>("BandeiraDoCartao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDoPagamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDoPedido")
                        .HasColumnType("int");

                    b.Property<string>("NomeNoCartaoDeCredito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDoCartaoDeCredito")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
